project_id:

subreddits:
  - legaladvice
  - relationship_advice

# Months must be between `2015_12` and `2017_12`
start_month: '2017_01'   
end_month: '2017_12'
max_posts: 1000   # by subreddit 
download_only: True

# Model training config
num_epochs: 5
gen_epochs: 1
batch_size: 128
prop_keep: 1.0
new_model: False

# Only applicable if new_model: True
model_config:
  rnn_layers: 2
  rnn_size: 128
  rnn_bidirectional: False
  max_length: 40
  dim_embeddings: 100
  word_level: False
